# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='messenger',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmessenger.proto\x12\tmessenger\"\x14\n\x04User\x12\x0c\n\x04user\x18\x01 \x01(\t\"Z\n\x04Text\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x13\n\x0b\x63ipher_text\x18\x03 \x01(\x0c\x12\x0b\n\x03tag\x18\x04 \x01(\x0c\x12\x0e\n\x06\x63ipher\x18\x05 \x01(\x0c\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"6\n\x10SendConfirmation\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tuser_list\x18\x02 \x01(\t2\xa6\x02\n\x0fMessengerServer\x12\x32\n\rMessageStream\x12\x0e.messenger.Key\x1a\x0f.messenger.Text0\x01\x12?\n\x0bSendMessage\x12\x0f.messenger.Text\x1a\x1b.messenger.SendConfirmation(\x01\x30\x01\x12<\n\x0cValidateUser\x12\x0f.messenger.User\x1a\x1b.messenger.SendConfirmation\x12/\n\x0bRegisterKey\x12\x0e.messenger.Key\x1a\x10.messenger.Empty\x12/\n\x0bReturnUsers\x12\x0f.messenger.User\x1a\x0f.messenger.Userb\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='messenger.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='messenger.User.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=50,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='messenger.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='messenger.Text.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='messenger.Text.receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cipher_text', full_name='messenger.Text.cipher_text', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='messenger.Text.tag', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cipher', full_name='messenger.Text.cipher', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=142,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='messenger.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messenger.Key.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=162,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='messenger.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=171,
)


_SENDCONFIRMATION = _descriptor.Descriptor(
  name='SendConfirmation',
  full_name='messenger.SendConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='messenger.SendConfirmation.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_list', full_name='messenger.SendConfirmation.user_list', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SendConfirmation'] = _SENDCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.User)
  ))
_sym_db.RegisterMessage(User)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), dict(
  DESCRIPTOR = _TEXT,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Text)
  ))
_sym_db.RegisterMessage(Text)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
  DESCRIPTOR = _KEY,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Key)
  ))
_sym_db.RegisterMessage(Key)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Empty)
  ))
_sym_db.RegisterMessage(Empty)

SendConfirmation = _reflection.GeneratedProtocolMessageType('SendConfirmation', (_message.Message,), dict(
  DESCRIPTOR = _SENDCONFIRMATION,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.SendConfirmation)
  ))
_sym_db.RegisterMessage(SendConfirmation)



_MESSENGERSERVER = _descriptor.ServiceDescriptor(
  name='MessengerServer',
  full_name='messenger.MessengerServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=230,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='MessageStream',
    full_name='messenger.MessengerServer.MessageStream',
    index=0,
    containing_service=None,
    input_type=_KEY,
    output_type=_TEXT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='messenger.MessengerServer.SendMessage',
    index=1,
    containing_service=None,
    input_type=_TEXT,
    output_type=_SENDCONFIRMATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ValidateUser',
    full_name='messenger.MessengerServer.ValidateUser',
    index=2,
    containing_service=None,
    input_type=_USER,
    output_type=_SENDCONFIRMATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterKey',
    full_name='messenger.MessengerServer.RegisterKey',
    index=3,
    containing_service=None,
    input_type=_KEY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnUsers',
    full_name='messenger.MessengerServer.ReturnUsers',
    index=4,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGERSERVER)

DESCRIPTOR.services_by_name['MessengerServer'] = _MESSENGERSERVER

# @@protoc_insertion_point(module_scope)
